---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"     
  
  pre_tasks:
    - name: "wait 250 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 200
        timeout: 220

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    - configure-alert-manager
    - configure-prometheus-server
    # - configure-node-exporter
   
  # ansible-playbook --key-file ../my-nd-key.pem -i .circleci/ansible/inventory.txt .circleci/ansible/playbook-prometheus-alert-manager.yml
  # ansible-playbook --key-file ../my-nd-key.pem -i .circleci/ansible/temp-inventory.txt .circleci/ansible/playbook-prometheus-alert-manager.yml